  /* code automatically generated by bin2c -- DO NOT EDIT */
  #ifndef __BEHAVIORS_POINTOFINTEREST_LUA_C__
  #define __BEHAVIORS_POINTOFINTEREST_LUA_C__
  /* behaviors/PointOfInterest.lua */
  static const unsigned int behaviorsPointOfInterestSize=90;
  static const char* behaviorsPointOfInterestName="behaviors/PointOfInterest.lua";
  static const char behaviorsPointOfInterest[]={
   77, 83, 99,114,105,112,116, 97, 98,108,101, 66,101,104, 97,118,105,111,114, 32,
 34, 80,111,105,110,116, 79,102, 73,110,116,101,114,101,115,116, 34, 32,123, 10,
  9,111,110, 66,101,103,105,110, 32, 61, 32,102,117,110, 99,116,105,111,110, 40,
115,101,108,102, 41, 10,  9,  9,112,114,105,110,116, 40, 34, 72,101,108,108,111,
 34, 41, 10,  9,101,110,100, 44, 10,125,
  };
  #endif/*__BEHAVIORS_POINTOFINTEREST_LUA_C__*/
  